from pydantic import BaseModel, Field, ConfigDict
from typing import Optional, TYPE_CHECKING, List
from datetime import date, datetime

from app.enums.enums import RoadDirection, AssetStatus, BarcodePosition

if TYPE_CHECKING:
    from app.schemas.contract_project import ContractProjectResponse
    from app.schemas.element_type import ElementTypeResponse
    from app.schemas.installer import InstallerResponse
    from app.schemas.macro_location import MacroLocationResponse


class AssetsReportRequest(BaseModel):
    contract_name: str = Field(
        ...,
        description="Name of the contract to filter assets",
    )
    include_photos: bool = Field(
        default=False,
        description="Whether to include asset photos in the report",
    )
    fecha_desde: datetime = Field(
        ...,
        description="Start datetime for filtering assets by created_at field (inclusive)",
    )
    fecha_hasta: datetime = Field(
        ...,
        description="End datetime for filtering assets by created_at field (inclusive)",
    )

    model_config = ConfigDict(extra="ignore")


class AssetBase(BaseModel):
    tag_bim: Optional[str] = Field(
        default=None,
        description="Id of the asset in the BIM system, provided by MOP (unique)",
        max_length=255,
    )
    id_interno: Optional[int] = Field(
        default=None,
        description="Id code generated by the company until MOP provides the BIM tag (unique)",
    )
    descripcion: Optional[str] = Field(
        default=None,
        description="Description of the asset",
        max_length=255,
    )
    fecha_instalacion: Optional[date] = Field(
        default=None,
        description="Installation date of the asset",
    )
    estado: Optional[AssetStatus] = Field(
        default=None,
        description="Status of the asset",
    )
    ubicacion_via: Optional[RoadDirection] = Field(
        default=None,
        description="Road direction where the asset is located",
    )
    ubicacion_codigo_barra: Optional[BarcodePosition] = Field(
        default=None,
        description="Position of the barcode on the asset",
    )
    nombre_foto_codigo_barra: Optional[str] = Field(
        default=None,
        description="Path to the photo of the barcode in the filesystem",
        max_length=255,
    )
    georeferenciacion: Optional[str] = Field(
        default=None,
        description="GPS coordinates extracted from the barcode picture",
        max_length=255,
    )
    # Foreign keys
    contract_project_id: Optional[int] = Field(
        default=None,
        description="ID of the associated contract project",
    )
    element_type_id: Optional[int] = Field(
        default=None,
        description="ID of the associated element type",
    )
    installer_id: Optional[int] = Field(
        default=None,
        description="ID of the associated installer",
    )
    macro_location_id: Optional[int] = Field(
        default=None,
        description="ID of the associated macro location",
    )
    kilometro: Optional[float] = Field(
        default=None,
        description="Kilometer marker where the asset is located",
    )

    model_config = ConfigDict(
        extra="ignore",
        use_enum_values=True,
        from_attributes=True,
    )


class AssetCreate(BaseModel):
    id_interno: int = Field(...)
    descripcion: str = Field(..., max_length=100)
    fecha_instalacion: date = Field(...)
    estado: AssetStatus = Field(...)
    ubicacion_via: RoadDirection = Field(...)
    ubicacion_codigo_barra: BarcodePosition = Field(...)
    georeferenciacion: str = Field(..., max_length=255)
    contract_project_id: int = Field(...)
    element_type_id: int = Field(...)
    installer_id: int = Field(...)

    model_config = ConfigDict(
        extra="ignore",
        use_enum_values=True,
        from_attributes=True,
    )


class AssetBulkCreate(BaseModel):
    assets: list[AssetCreate] = Field(...)

    model_config = ConfigDict(
        extra="ignore",
        from_attributes=True,
    )


class AssetUpdate(AssetBase):
    nombre_foto_codigo_barra: Optional[str] = Field(
        default=None,
        exclude=True,
        description="Excluded from updates - managed server-side only",
    )


class AssetResponse(AssetBase):
    id: int
    version: int
    created_at: datetime
    updated_at: datetime


class AssetDetailResponse(AssetBase):
    id: int
    version: int
    created_at: datetime
    updated_at: datetime
    kilometro: Optional[float] = Field(
        default=None,
        description="Kilometer marker where the asset is located",
    )

    contract_project: "ContractProjectResponse" = Field(
        ...,
        description="Associated contract project details",
    )
    element_type: "ElementTypeResponse" = Field(
        ...,
        description="Associated element type details",
    )
    installer: "InstallerResponse" = Field(
        ...,
        description="Associated installer details",
    )
    macro_location: Optional["MacroLocationResponse"] = Field(
        default=None,
        description="Associated macro location details",
    )

    model_config = ConfigDict(
        extra="ignore",
        use_enum_values=True,
        from_attributes=True,
    )


class AssetWithPhotoResponse(AssetDetailResponse):
    """Asset response that includes the photo in base64 format if available"""

    photo_base64: Optional[str] = Field(
        default=None,
        description="Base64 encoded photo of the barcode, only included if photo exists in filesystem",
    )


"""Asset Sync Schemas"""


class AssetSyncResponse(BaseModel):
    created: int
    conflictive: int
    total: int
    failed: int = Field(
        default=0,
        description="Number of assets that failed to insert into both asset and conflictive_asset tables",
    )
    failed_id_internos: List[int] = Field(
        default_factory=list,
        description="List of id_internos that failed to be inserted - mobile apps should retry these",
    )

    model_config = ConfigDict(extra="ignore")


class AssetSyncRequest(BaseModel):
    fecha_instalacion_desde: date = Field(
        ...,
        description="Start date for filtering assets by installation date (inclusive)",
    )
    exclude_ids_internos: Optional[List[int]] = Field(
        default=[],
        description="List of id_internos that the client already has and should be excluded from the response",
    )
    limit: Optional[int] = Field(
        default=1000,
        ge=1,
        le=5000,
        description="Maximum number of assets to return (1-5000)",
    )
    offset: Optional[int] = Field(
        default=0,
        ge=0,
        description="Number of assets to skip for pagination",
    )

    model_config = ConfigDict(extra="ignore")


class AssetSyncItem(BaseModel):
    """Lightweight asset model for mobile sync - no relationships, no photos"""

    id: int
    tag_bim: Optional[str] = None
    id_interno: int
    descripcion: Optional[str] = None
    fecha_instalacion: Optional[date] = None
    estado: Optional[AssetStatus] = None
    ubicacion_via: Optional[RoadDirection] = None
    ubicacion_codigo_barra: Optional[BarcodePosition] = None
    georeferenciacion: Optional[str] = None
    contract_project_id: Optional[int] = None
    element_type_id: Optional[int] = None
    installer_id: Optional[int] = None
    macro_location_id: Optional[int] = None

    model_config = ConfigDict(extra="ignore", from_attributes=True)


class AssetSyncDataResponse(BaseModel):
    assets: List[AssetSyncItem]
    total_available: int
    returned_count: int
    has_more: bool
    next_offset: Optional[int] = None

    model_config = ConfigDict(extra="ignore")


"""Photo Upload Schemas"""


class PhotoUploadResponse(BaseModel):
    success: bool
    id_interno: int
    photo_name: Optional[str] = None
    error_message: Optional[str] = None

    model_config = ConfigDict(extra="ignore", from_attributes=True)


class BulkPhotoUploadResponse(BaseModel):
    total_processed: int
    total_successful: int
    total_failed: int
    results: List[PhotoUploadResponse]

    model_config = ConfigDict(extra="ignore", from_attributes=True)


class AssetsReportRequest(BaseModel):
    contract_name: str = Field(
        ...,
        description="Name of the contract to filter assets",
    )
    include_photos: Optional[bool] = Field(
        default=None,
        description="Whether to include asset photos in the report",
    )
    fecha_desde: datetime = Field(
        ...,
        description="Start datetime for filtering assets by created_at field (inclusive)",
    )
    fecha_hasta: datetime = Field(
        ...,
        description="End datetime for filtering assets by created_at field (inclusive)",
    )
    element_type: Optional[str] = Field(
        default=None,
        description="Element type name to filter assets",
    )
    asset_status: Optional[AssetStatus] = Field(
        default=None,
        description="Status of the asset to filter by",
    )

    model_config = ConfigDict(extra="ignore")


class ReportTaskResponse(BaseModel):
    """Response when a report generation task is initiated"""

    task_id: str = Field(
        ...,
        description="Unique task identifier (UUID) for the report generation",
    )
    status: str = Field(
        ...,
        description="Current status: 'pending', 'completed', 'failed'",
    )
    message: str = Field(
        ...,
        description="Human-readable message about the task status",
    )

    model_config = ConfigDict(extra="ignore")


class ReportStatusResponse(BaseModel):
    """Response when checking the status of a report generation task"""

    task_id: str = Field(
        ...,
        description="Unique task identifier (UUID) for the report generation",
    )
    status: str = Field(
        ...,
        description="Current status: 'pending', 'completed', 'failed'",
    )
    message: str = Field(
        ...,
        description="Human-readable message about the task status",
    )

    model_config = ConfigDict(extra="ignore")
