from pydantic import BaseModel, Field, ConfigDict
from typing import Optional
from datetime import date, datetime

from app.enums.enums import RoadDirection, AssetStatus, BarcodePosition


class ConflictiveAssetBase(BaseModel):
    id_interno: Optional[int] = Field(
        default=None,
        description="Id code generated by the company until MOP provides the BIM tag (unique)",
    )
    descripcion: Optional[str] = Field(
        default=None,
        description="Description of the asset",
        max_length=100,
    )
    fecha_instalacion: Optional[date] = Field(
        default=None,
        description="Installation date of the asset",
    )
    estado: Optional[AssetStatus] = Field(
        default=None,
        description="Status of the asset",
    )
    ubicacion_via: Optional[RoadDirection] = Field(
        default=None,
        description="Road direction where the asset is located",
    )
    ubicacion_codigo_barra: Optional[BarcodePosition] = Field(
        default=None,
        description="Position of the barcode on the asset",
    )
    nombre_foto_codigo_barra: Optional[str] = Field(
        default=None,
        description="Path to the photo of the barcode in the filesystem",
        max_length=255,
    )
    georeferenciacion: Optional[str] = Field(
        default=None,
        description="GPS coordinates extracted from the barcode picture",
        max_length=255,
    )
    # Foreign keys
    contract_project_id: Optional[int] = Field(
        default=None,
        description="ID of the associated contract project",
    )
    element_type_id: Optional[int] = Field(
        default=None,
        description="ID of the associated element type",
    )
    installer_id: Optional[int] = Field(
        default=None,
        description="ID of the associated installer",
    )

    model_config = ConfigDict(
        extra="ignore",
        use_enum_values=True,
        from_attributes=True,
    )


class ConflictiveAssetCreate(ConflictiveAssetBase):
    id_interno: int = Field(...)
    descripcion: str = Field(..., max_length=100)
    fecha_instalacion: date = Field(...)
    estado: AssetStatus = Field(...)
    ubicacion_via: RoadDirection = Field(...)
    ubicacion_codigo_barra: BarcodePosition = Field(...)
    georeferenciacion: str = Field(..., max_length=255)
    contract_project_id: int = Field(...)
    element_type_id: int = Field(...)
    installer_id: int = Field(...)


class ConflictiveAssetResponse(ConflictiveAssetBase):
    id: int
    created_at: datetime
    updated_at: datetime
