from sqlalchemy import (
    Integer,
    BigInteger,
    String,
    Date,
    Enum as SQLAlchemyEnum,
    ForeignKey,
    Float,
)
from sqlalchemy.orm import relationship, Mapped, mapped_column
from typing import Optional, TYPE_CHECKING
from datetime import date, datetime

from app.db.base_class import Base, TimestampMixin
from app.enums.enums import RoadDirection, AssetStatus, BarcodePosition

if TYPE_CHECKING:
    from .contract_project import ContractProject
    from .element_type import ElementType
    from .installer import Installer
    from .macro_location import MacroLocation


class Asset(Base, TimestampMixin):
    __tablename__ = "asset"

    id: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        primary_key=True,
        autoincrement=True,
    )
    # Identifiers
    """Id of the asset in the BIM system, provided by MOP, not existent yet"""
    tag_bim: Mapped[Optional[str]] = mapped_column(
        String(255),
        nullable=True,
        unique=True,
    )
    """Id code generated by the company until MOP provides the BIM tag"""
    id_interno: Mapped[int] = mapped_column(
        BigInteger,
        nullable=False,
        unique=True,
    )
    descripcion: Mapped[str] = mapped_column(
        String(255),
        nullable=True,
    )
    fecha_instalacion: Mapped[date] = mapped_column(
        Date,
        nullable=False,
    )

    # Enums
    estado: Mapped[AssetStatus] = mapped_column(
        SQLAlchemyEnum(AssetStatus),
        nullable=False,
    )
    ubicacion_via: Mapped[RoadDirection] = mapped_column(
        SQLAlchemyEnum(RoadDirection),
        nullable=False,
    )
    ubicacion_codigo_barra: Mapped[BarcodePosition] = mapped_column(
        SQLAlchemyEnum(BarcodePosition),
        nullable=False,
    )

    # Photos fields (stored in filesystem)
    nombre_foto_codigo_barra: Mapped[Optional[str]] = mapped_column(
        String(255),
        nullable=True,
    )

    # GPS coordinates (extracted from barcode picture)
    georeferenciacion: Mapped[Optional[str]] = mapped_column(
        String(255),
        nullable=True,
    )

    kilometro: Mapped[Optional[float]] = mapped_column(
        Float,
        nullable=True,
    )

    # Fields to synchronize local dbs with central db
    version: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=1,
    )
    # created_at y updated_at vienen del TimestampMixin con manejo UTC correcto

    # Foreign Keys
    contract_project_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("contract_project.id"),
        nullable=False,
        index=True,
    )
    element_type_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("element_type.id"),
        nullable=False,
        index=True,
    )
    installer_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("installer.id"),
        nullable=False,
        index=True,
    )
    macro_location_id: Mapped[Optional[int]] = mapped_column(
        Integer,
        ForeignKey("macro_location.id"),
        nullable=True,
        index=True,
    )

    # Relationships
    contract_project: Mapped["ContractProject"] = relationship(
        "ContractProject",
        foreign_keys=[contract_project_id],
        lazy="select",
    )
    element_type: Mapped["ElementType"] = relationship(
        "ElementType",
        foreign_keys=[element_type_id],
        lazy="select",
    )
    installer: Mapped["Installer"] = relationship(
        "Installer",
        foreign_keys=[installer_id],
        lazy="select",
    )
    macro_location: Mapped[Optional["MacroLocation"]] = relationship(
        "MacroLocation",
        foreign_keys=[macro_location_id],
        lazy="select",
    )
